import type { User, SkillScore, Course, Assessment, KnowledgeItem, TeamMember, OrgDepartmentMetrics } from '../types';

export const INITIAL_SKILLS: SkillScore[] = [
  { skillId: 'spring-boot', skillName: 'Java Spring Boot', current: 45, target: 80, priority: 'HIGH', category: 'Technical' },
  { skillId: 'cloud-computing', skillName: 'Cloud Computing', current: 52, target: 75, priority: 'HIGH', category: 'Technical' },
  { skillId: 'communication', skillName: 'Communication', current: 68, target: 85, priority: 'MEDIUM', category: 'Soft Skills' },
  { skillId: 'react', skillName: 'React & Frontend', current: 85, target: 90, priority: 'LOW', category: 'Technical' },
  { skillId: 'ai-ml', skillName: 'AI & Machine Learning', current: 40, target: 70, priority: 'HIGH', category: 'Technical' },
  { skillId: 'cybersecurity', skillName: 'Cyber Security', current: 60, target: 75, priority: 'MEDIUM', category: 'Technical' },
  { skillId: 'leadership', skillName: 'Leadership', current: 55, target: 80, priority: 'MEDIUM', category: 'Leadership' },
  { skillId: 'problem-solving', skillName: 'Problem Solving', current: 78, target: 85, priority: 'LOW', category: 'Soft Skills' },
];

export const MOCK_USERS: Record<string, User> = {
  learner: {
    id: 'usr-001',
    name: 'Rajamurugan',
    email: 'rajamurugan@corp.org',
    role: 'LEARNER',
    department: 'Engineering',
    title: 'Founder & Platform Lead',
    experience: 'Founder & Lead Developer',
    avatar: '/rajamurugan.jpg',
    streak: 7,
    learningHours: 24,
    coursesCompleted: 8,
    overallSkillScore: 72,
    skills: [...INITIAL_SKILLS],
  },
  manager: {
    id: 'usr-002',
    name: 'Priya Kumar',
    email: 'priya.kumar@corp.org',
    role: 'MANAGER',
    department: 'Engineering',
    title: 'Engineering Manager',
    experience: '8 Years',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    streak: 14,
    learningHours: 42,
    coursesCompleted: 15,
    overallSkillScore: 84,
    skills: [
      { skillId: 'leadership', skillName: 'Leadership', current: 88, target: 90, priority: 'LOW', category: 'Leadership' },
      { skillId: 'communication', skillName: 'Communication', current: 92, target: 95, priority: 'LOW', category: 'Soft Skills' },
      { skillId: 'cloud-computing', skillName: 'Cloud Computing', current: 75, target: 85, priority: 'MEDIUM', category: 'Technical' },
      { skillId: 'spring-boot', skillName: 'Java Spring Boot', current: 70, target: 80, priority: 'LOW', category: 'Technical' },
    ],
  },
  admin: {
    id: 'usr-003',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@corp.org',
    role: 'ADMIN',
    department: 'L&D Management',
    title: 'Head of Capacity Building',
    experience: '12 Years',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    streak: 21,
    learningHours: 65,
    coursesCompleted: 24,
    overallSkillScore: 91,
    skills: [
      { skillId: 'leadership', skillName: 'Leadership', current: 95, target: 95, priority: 'LOW', category: 'Leadership' },
      { skillId: 'communication', skillName: 'Communication', current: 94, target: 95, priority: 'LOW', category: 'Soft Skills' },
    ],
  },
};

export const MOCK_COURSES: Course[] = [
  {
    id: 'crs-101',
    title: 'Spring Boot Fundamentals',
    description: 'Master backend architecture, REST API design, dependency injection, and data persistence with Spring Data JPA.',
    instructor: 'Dr. Rajesh Patel',
    duration: '4h 30m',
    difficulty: 'Intermediate',
    category: 'Programming',
    skillId: 'spring-boot',
    skillName: 'Java Spring Boot',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=600',
    progress: 35,
    completed: false,
    enrolled: true,
    modules: [
      {
        id: 'mod-1',
        title: 'Module 1: Core Spring Concepts & Dependency Injection',
        description: 'Understand inversion of control, bean scopes, and component scanning.',
        resources: [
          { id: 'res-1', title: 'Spring Beans & Annotations Deep Dive', duration: '25 mins', type: 'video', completed: true },
          { id: 'res-2', title: 'Spring Core Cheatsheet PDF', duration: '10 mins', type: 'pdf', completed: true },
        ],
      },
      {
        id: 'mod-2',
        title: 'Module 2: Building RESTful APIs with Spring MVC',
        description: 'Create controllers, request mappings, response payloads, and HTTP status handling.',
        resources: [
          { id: 'res-3', title: 'Building REST Controllers in Spring', duration: '35 mins', type: 'video', completed: false },
          { id: 'res-4', title: 'Hands-on Exercise: Create CRUD Endpoint', duration: '40 mins', type: 'exercise', completed: false },
        ],
      },
      {
        id: 'mod-3',
        title: 'Module 3: Persistence with Spring Data JPA & PostgreSQL',
        description: 'Entity mapping, repositories, custom queries, and database migrations.',
        resources: [
          { id: 'res-5', title: 'Spring Data JPA Masterclass', duration: '45 mins', type: 'video', completed: false },
        ],
      },
      {
        id: 'mod-4',
        title: 'Module 4: Spring Security & JWT Auth',
        description: 'Securing web services using JSON Web Tokens and role-based access control.',
        resources: [
          { id: 'res-6', title: 'Spring Security 6 Architecture Guide', duration: '30 mins', type: 'article', completed: false },
        ],
      },
    ],
  },
  {
    id: 'crs-102',
    title: 'Cloud Infrastructure & AWS Architecture',
    description: 'Learn modern cloud containerization, Kubernetes cluster orchestration, and serverless architectures.',
    instructor: 'Sarah Jenkins',
    duration: '6h 15m',
    difficulty: 'Intermediate',
    category: 'Cloud Computing',
    skillId: 'cloud-computing',
    skillName: 'Cloud Computing',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=600',
    progress: 52,
    completed: false,
    enrolled: true,
    modules: [
      {
        id: 'mod-102-1',
        title: 'Module 1: AWS Core Infrastructure',
        description: 'VPC, EC2, S3, and IAM security policies.',
        resources: [
          { id: 'res-102-1', title: 'AWS Cloud Foundations Video', duration: '40 mins', type: 'video', completed: true },
        ],
      },
    ],
  },
  {
    id: 'crs-103',
    title: 'AI & Generative LLM Engineering',
    description: 'Understand prompt engineering, transformer architecture, fine-tuning, and open-source model deployment.',
    instructor: 'Dr. Amit Verma',
    duration: '5h 00m',
    difficulty: 'Advanced',
    category: 'AI & Machine Learning',
    skillId: 'ai-ml',
    skillName: 'AI & Machine Learning',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&q=80&w=600',
    progress: 10,
    completed: false,
    enrolled: true,
    modules: [],
  },
  {
    id: 'crs-104',
    title: 'Enterprise Leadership & Team Management',
    description: 'Build strategic communication skills, conflict resolution, delegation, and continuous team capability frameworks.',
    instructor: 'Elena Rostova',
    duration: '3h 45m',
    difficulty: 'Intermediate',
    category: 'Leadership',
    skillId: 'leadership',
    skillName: 'Leadership',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=600',
    progress: 100,
    completed: true,
    enrolled: true,
    modules: [],
  },
  {
    id: 'crs-105',
    title: 'Cyber Security Essentials & Zero Trust Architecture',
    description: 'Identify vulnerability patterns, secure enterprise endpoints, and implement robust authentication controls.',
    instructor: 'Marcus Sterling',
    duration: '4h 00m',
    difficulty: 'Beginner',
    category: 'Cyber Security',
    skillId: 'cybersecurity',
    skillName: 'Cyber Security',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=600',
    progress: 60,
    completed: false,
    enrolled: true,
    modules: [],
  },
];

export const MOCK_ASSESSMENTS: Assessment[] = [
  {
    id: 'asm-101',
    title: 'Spring Boot Competency & REST API Assessment',
    skillId: 'spring-boot',
    skillName: 'Java Spring Boot',
    difficulty: 'Intermediate',
    questionCount: 5,
    passingScore: 70,
    timeLimitMinutes: 10,
    questions: [
      {
        id: 'q1',
        question: 'Which annotation in Spring Boot is used to auto-configure components and mark the primary application class?',
        options: ['@SpringBootApplication', '@EnableAutoConfiguration', '@ComponentScan', '@Configuration'],
        correctAnswerIndex: 0,
        explanation: '@SpringBootApplication combines @Configuration, @EnableAutoConfiguration, and @ComponentScan with default attributes.',
      },
      {
        id: 'q2',
        question: 'In Spring Data JPA, what does the @Entity annotation declare?',
        options: [
          'A class mapped to a relational database table',
          'A REST controller endpoint',
          'A singleton service bean',
          'An asynchronous background task',
        ],
        correctAnswerIndex: 0,
        explanation: '@Entity marks a Java POJO as a persistent JPA entity mapped to a table.',
      },
      {
        id: 'q3',
        question: 'Which HTTP method should be idempotent according to REST standards?',
        options: ['POST', 'PUT', 'PATCH', 'CONNECT'],
        correctAnswerIndex: 1,
        explanation: 'PUT operations are idempotent; executing identical PUT requests multiple times yields the same server state.',
      },
      {
        id: 'q4',
        question: 'How do you inject a property value from application.properties into a Spring Bean?',
        options: ['@Value("${property.name}")', '@PropertyInject("property.name")', '@Env("property.name")', '@AutowiredProperty'],
        correctAnswerIndex: 0,
        explanation: '@Value("${property.name}") is the standard Spring annotation for injecting configuration values.',
      },
      {
        id: 'q5',
        question: 'What is the primary benefit of Spring Boot Actuator?',
        options: [
          'Provides production-ready features like health checks, metrics, and application audit info',
          'Generates frontend HTML components',
          'Compiles Java bytecode to native machine code',
          'Encrypts database passwords automatically',
        ],
        correctAnswerIndex: 0,
        explanation: 'Actuator exposes built-in management endpoints (/actuator/health, /actuator/metrics) for monitoring.',
      },
    ],
  },
  {
    id: 'asm-102',
    title: 'Cloud Infrastructure & AWS Benchmark',
    skillId: 'cloud-computing',
    skillName: 'Cloud Computing',
    difficulty: 'Intermediate',
    questionCount: 4,
    passingScore: 75,
    timeLimitMinutes: 8,
    questions: [
      {
        id: 'q102-1',
        question: 'Which AWS service provides serverless compute execution based on event triggers?',
        options: ['AWS Lambda', 'Amazon EC2', 'Amazon ECS', 'AWS Elastic Beanstalk'],
        correctAnswerIndex: 0,
        explanation: 'AWS Lambda runs code in response to events without managing virtual servers.',
      },
      {
        id: 'q102-2',
        question: 'What does a VPC Security Group act as in AWS network infrastructure?',
        options: [
          'Stateful virtual firewall for controlling EC2 instance traffic',
          'Domain Name Server',
          'Stateless subnet-level filter',
          'Load Balancer distribution rule',
        ],
        correctAnswerIndex: 0,
        explanation: 'Security Groups act as stateful firewalls at the instance level.',
      },
    ],
  },
];

export const MOCK_KNOWLEDGE_ITEMS: KnowledgeItem[] = [
  {
    id: 'knw-001',
    title: 'Spring Boot 3.x Enterprise Architecture Standard',
    description: 'Comprehensive guidelines for controller design, exception handling, data mapping, and microservice logging standards across all engineering teams.',
    category: 'Technical Guides',
    authorName: 'Rajamurugan',
    authorRole: 'Founder & Platform Lead',
    department: 'Engineering',
    date: '2026-08-28',
    type: 'pdf',
    tags: ['Spring Boot', 'Java', 'Architecture', 'REST'],
    downloads: 142,
    views: 530,
  },
  {
    id: 'knw-002',
    title: 'AWS Cloud Security Compliance Blueprint',
    description: 'Mandatory security rules for IAM role policies, S3 bucket encryption, VPC peering, and secret rotation in production deployments.',
    category: 'Best Practices',
    authorName: 'Priya Kumar',
    authorRole: 'Engineering Manager',
    department: 'Engineering',
    date: '2026-09-02',
    type: 'pdf',
    tags: ['AWS', 'Security', 'Cloud', 'Compliance'],
    downloads: 98,
    views: 310,
  },
  {
    id: 'knw-003',
    title: 'SIH Competency Assessment Framework & AI Rubric',
    description: 'Documentation on how AI-driven quiz generation aligns with organizational baseline goals and dynamically calculates employee skill deltas.',
    category: 'Project Knowledge',
    authorName: 'Rahul Sharma',
    authorRole: 'Head of Capacity Building',
    department: 'L&D Management',
    date: '2026-09-10',
    type: 'presentation',
    tags: ['Capacity Building', 'AI', 'Competency', 'SIH26075'],
    downloads: 215,
    views: 890,
  },
  {
    id: 'knw-004',
    title: 'React 19 & Modern Web Application State Design',
    description: 'Guidelines for managing global context, async server state, component modularity, and micro-interactions.',
    category: 'Technical Guides',
    authorName: 'Rajamurugan',
    authorRole: 'Founder & Platform Lead',
    department: 'Engineering',
    date: '2026-09-05',
    type: 'article',
    tags: ['React', 'Frontend', 'TypeScript'],
    downloads: 110,
    views: 420,
  },
];

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Rajamurugan',
    email: 'rajamurugan@corp.org',
    avatar: '/rajamurugan.jpg',
    department: 'Engineering',
    title: 'Founder & Lead Developer',
    overallScore: 72,
    activeCourses: 3,
    skills: { 'Spring Boot': 45, 'Cloud': 52, 'React': 85, 'Communication': 68, 'Leadership': 55, 'AI/ML': 40 },
  },
  {
    id: 'tm-2',
    name: 'Priya Kumar',
    email: 'priya.k@corp.org',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    department: 'Engineering',
    title: 'Tech Lead',
    overallScore: 84,
    activeCourses: 2,
    skills: { 'Spring Boot': 70, 'Cloud': 75, 'React': 90, 'Communication': 92, 'Leadership': 88, 'AI/ML': 65 },
  },
  {
    id: 'tm-3',
    name: 'Rahul Sharma',
    email: 'rahul.s@corp.org',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    department: 'Engineering',
    title: 'Senior Architect',
    overallScore: 91,
    activeCourses: 1,
    skills: { 'Spring Boot': 92, 'Cloud': 88, 'React': 82, 'Communication': 94, 'Leadership': 95, 'AI/ML': 80 },
  },
  {
    id: 'tm-4',
    name: 'Meena Devi',
    email: 'meena.d@corp.org',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    department: 'Engineering',
    title: 'Frontend Engineer',
    overallScore: 68,
    activeCourses: 4,
    skills: { 'Spring Boot': 35, 'Cloud': 45, 'React': 88, 'Communication': 75, 'Leadership': 50, 'AI/ML': 30 },
  },
  {
    id: 'tm-5',
    name: 'Arun Kumar',
    email: 'arun.k@corp.org',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    department: 'Engineering',
    title: 'DevOps Engineer',
    overallScore: 76,
    activeCourses: 2,
    skills: { 'Spring Boot': 50, 'Cloud': 90, 'React': 40, 'Communication': 65, 'Leadership': 60, 'AI/ML': 55 },
  },
];

export const MOCK_ORG_DEPARTMENTS: OrgDepartmentMetrics[] = [
  {
    department: 'Engineering',
    learnerCount: 145,
    avgSkillScore: 74,
    activeCourses: 320,
    criticalGaps: 42,
    skills: { 'Java Spring Boot': 58, 'Cloud Computing': 65, 'AI/ML': 48, 'React': 84, 'Communication': 72, 'Leadership': 60 },
  },
  {
    department: 'HR & Talent',
    learnerCount: 42,
    avgSkillScore: 81,
    activeCourses: 95,
    criticalGaps: 12,
    skills: { 'Java Spring Boot': 20, 'Cloud Computing': 30, 'AI/ML': 40, 'React': 25, 'Communication': 94, 'Leadership': 88 },
  },
  {
    department: 'Operations',
    learnerCount: 88,
    avgSkillScore: 70,
    activeCourses: 180,
    criticalGaps: 28,
    skills: { 'Java Spring Boot': 35, 'Cloud Computing': 55, 'AI/ML': 50, 'React': 30, 'Communication': 78, 'Leadership': 72 },
  },
  {
    department: 'Finance',
    learnerCount: 64,
    avgSkillScore: 77,
    activeCourses: 110,
    criticalGaps: 18,
    skills: { 'Java Spring Boot': 15, 'Cloud Computing': 45, 'AI/ML': 62, 'React': 20, 'Communication': 82, 'Leadership': 76 },
  },
  {
    department: 'Marketing',
    learnerCount: 52,
    avgSkillScore: 72,
    activeCourses: 130,
    criticalGaps: 22,
    skills: { 'Java Spring Boot': 10, 'Cloud Computing': 40, 'AI/ML': 68, 'React': 45, 'Communication': 90, 'Leadership': 68 },
  },
];
